import { Product } from "./Interfaces/interface";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Designer Lampe',
    price: 899,
    description: 'Hochwertige Lapme; Eine Designer Lampe; 5 Jahre Garantie',
    image: 'lampe.jpg',
    category: { id: 1, name: 'Indoor' },
    bestseller: true,
  },
  {
    id: 2,
    name: 'Rucksack',
    price: 49,
    description: 'Hochwertiger Rucksack; Wurde für Intensive Outdoor aktivitäten entwickelt; 30 Tage Geld zurück Garantie',
    image: 'rucksack.jpg',
    category: { id: 2, name: 'Outdoor' },
    bestseller: true,
  },
  {
    id: 3,
    name: 'Beamer',
    price: 499,
    description: 'Leistungsstarkter Beamer; Perfekt für ein Heimkino; Studioreife Lautsprecher für ein immersives Erlebnis; 3 Jahre Garantie',
    image: 'beamer.png',
    category: { id: 3, name: 'Multimedia' },
    bestseller: true,
  },
  {
    id: 4,
    name: 'Kopfhörer',
    price: 39,
    description: 'Kopfhörer für den Alltag; Sehr Gute Musik Qualität; Nur mit IPhone Kompatibel; Keine Garantie',
    image: 'kopfhörer.jpg',
    category: { id: 3, name: 'Mutimedia'},
    bestseller: false,
  },
  {
    id: 5,
    name: 'Basketball',
    price: 69,
    description: 'Basketball für Outdoor Aktivitäten.; Sehr Hohe Qualität; 30 Tage Geld zurück Garantie',
    image: 'basketball.jpg',
    category: { id: 2, name: 'Outdoor'},
    bestseller: false,
  },
  {
    id: 6,
    name: 'Stuhl',
    price: 119,
    description: 'Sehr ergonomischer Stuhl; Perfekt für Indoor Anwendungen; 3 Jahre Garantie',
    image: 'stuhl.jpg',
    category: { id: 1, name: 'Indoor'},
    bestseller: false,
  },
  {
    id: 7,
    name: 'Flasche',
    price: 9,
    description: 'Unzerstörbare Flasche; Speziell für intensive Outdoor Aktivitäten entwickelt.; Mehrfach verwendung möglich.; Aus recycelten Materialien hergestellt.',
    image: 'bottle.jpg',
    category: { id: 2, name: 'Outdoor'},
    bestseller: false,
  },
  {
    id: 8,
    name: 'Zelt',
    price: 299,
    description: 'Perfekt für Ausflüge im Sommer; Wird nicht heiss wenn es in der Sonne steht.; Sehr Stabil; Isolierte Innenwände.',
    image: 'zelt.jpg',
    category: { id: 2, name: 'Outdoor'},
    bestseller: false,
  },
]