import { Product } from "./Interfaces/interface";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Designer Lampe',
    price: 899,
    description: '',
    image: 'lampe.jpg',
    category: { id: 1, name: 'Indoor' },
    bestseller: true,
  },
  {
    id: 2,
    name: 'Rucksack',
    price: 49,
    description: '',
    image: 'rucksack.jpg',
    category: { id: 2, name: 'Outdoor' },
    bestseller: true,
  },
  {
    id: 3,
    name: 'Beamer',
    price: 499,
    description: '',
    image: 'beamer.png',
    category: { id: 3, name: 'Multimedia' },
    bestseller: true,
  },
  {
    id: 4,
    name: 'Kopfhörer',
    price: 39,
    description: '',
    image: 'kopfhörer.jpg',
    category: { id: 3, name: 'Mutimedia'},
    bestseller: false,
  },
  {
    id: 5,
    name: 'Basketball',
    price: 69,
    description: '',
    image: 'basketball.jpg',
    category: { id: 2, name: 'Outdoor'},
    bestseller: false,
  },
  {
    id: 6,
    name: 'Stuhl',
    price: 119,
    description: '',
    image: 'stuhl.jpg',
    category: { id: 1, name: 'Indoor'},
    bestseller: false,
  },
  {
    id: 7,
    name: 'Flasche',
    price: 9,
    description: '',
    image: 'bottle.jpg',
    category: { id: 2, name: 'Outdoor'},
    bestseller: false,
  },
  {
    id: 8,
    name: 'Zelt',
    price: 299,
    description: '',
    image: 'zelt.jpg',
    category: { id: 2, name: 'Outdoor'},
    bestseller: false,
  },
]